import { test, expect } from '@playwright/test';

test.describe.serial('Student and admin portal', () => {
  test('typing, course search, submission reset, and duplicate confirmation', async ({ page }) => {
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('/');
    const name = page.getByRole('textbox', { name: /Full name/ });
    await name.fill('Amara');
    await name.pressSequentially(' Okafor', { delay: 10 });
    await expect(name).toHaveValue('Amara Okafor');
    await page.getByRole('textbox', { name: /Email address/ }).fill('browser-student@example.com');
    await page.getByRole('textbox', { name: /Phone number/ }).fill('+234 801 234 5678');
    await page.getByRole('textbox', { name: /Your location/ }).fill('Lagos, Nigeria');
    const search = page.getByRole('textbox', { name: 'Search courses' });
    await search.pressSequentially('Computer', { delay: 10 });
    await expect(search).toHaveValue('Computer');
    await page.locator('.course-result').filter({ hasText: 'Computer Science' }).click();
    await page.getByRole('combobox', { name: /Preferred intake/ }).selectOption({ label: 'January 2027' });
    await page.getByRole('combobox', { name: /Preferred study destination/ }).selectOption('United Kingdom');
    const eventOption = await page.locator('select[name="event_id"] option').nth(1).getAttribute('value');
    await page.locator('select[name="event_id"]').selectOption(eventOption);
    await page.getByRole('button', { name: 'Send my interest' }).click();
    await expect(page.locator('.success')).toContainText('Reference: TGM-');
    await expect(page.getByRole('alert')).toHaveCount(0);
    await expect(name).toHaveValue('');
    await expect(search).toHaveValue('');
    const reference = await page.locator('.success strong').textContent();
    await name.fill('Amara Okafor');
    await page.getByRole('textbox', { name: /Email address/ }).fill('browser-student@example.com');
    await page.getByRole('textbox', { name: /Phone number/ }).fill('+234 801 234 5678');
    await page.getByRole('textbox', { name: /Your location/ }).fill('Lagos, Nigeria');
    await search.fill('Computer');
    await page.locator('.course-result').filter({ hasText: 'Computer Science' }).click();
    await page.getByRole('combobox', { name: /Preferred intake/ }).selectOption({ label: 'January 2027' });
    await page.getByRole('combobox', { name: /Preferred study destination/ }).selectOption('United Kingdom');
    await page.locator('select[name="event_id"]').selectOption(eventOption);
    await page.getByRole('button', { name: 'Send my interest' }).click();
    await expect(page.locator('.success')).toContainText('recent submission');
    await expect(page.locator('.success strong')).toHaveText(reference);
    expect(errors).toEqual([]);
  });

  test('admin navigation, login, notes, course/event creation, and signed-in student form', async ({ page }) => {
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('/');
    await page.getByRole('button', { name: 'Admin', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Admin sign in' })).toBeVisible();
    await page.getByRole('button', { name: /Student portal/ }).click();
    await expect(page.getByRole('textbox', { name: /Full name/ })).toBeVisible();
    await page.getByRole('button', { name: 'Admin', exact: true }).click();
    await page.getByRole('textbox', { name: 'Username' }).fill('e2e-admin');
    await page.getByLabel('Password', { exact: true }).fill('E2eOnly934!');
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Overview', exact: true })).toBeVisible();
    await page.getByRole('button', { name: /^Inquiries/ }).click();
    await page.getByPlaceholder('Name, email, phone or reference').fill('browser-student');
    await page.locator('tbody tr').filter({ hasText: 'browser-student@example.com' }).click();
    await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('Contacted');
    await page.getByLabel('Internal notes').fill('Called student about accommodation.');
    await page.getByRole('button', { name: 'Save changes' }).click();
    await expect(page.locator('.status-pill')).toHaveText('Contacted');
    await page.getByRole('button', { name: 'Courses', exact: true }).click();
    await page.getByPlaceholder('Course name', { exact: true }).fill('Browser QA Course');
    await page.getByPlaceholder('Annual tuition (NGN)').fill('19000');
    await page.getByPlaceholder('Study city').fill('London');
    await page.getByRole('button', { name: 'Add course', exact: true }).click();
    await expect(page.locator('.manage-row').filter({ hasText: 'Browser QA Course' })).toBeVisible();
    await expect(page.getByPlaceholder('Course name', { exact: true })).toHaveValue('');
    const courseRow = page.locator('.manage-row').filter({ hasText: 'Browser QA Course' });
    await courseRow.getByRole('button', { name: 'Edit', exact: true }).click();
    const courseEditor = page.getByRole('dialog');
    await courseEditor.getByRole('spinbutton', { name: 'Annual tuition (NGN)' }).fill('20000');
    await courseEditor.getByRole('checkbox', { name: 'August', exact: true }).check();
    await courseEditor.getByRole('button', { name: 'Save changes' }).click();
    await expect(courseRow).toContainText('20,000');
    await expect(courseRow).toContainText('₦');
    await expect(courseRow).toContainText('August');
    page.once('dialog', dialog => dialog.accept());
    await courseRow.getByRole('button', { name: 'Deactivate', exact: true }).click();
    await expect(courseRow.getByText('Inactive', { exact: true })).toBeVisible();
    await courseRow.getByRole('button', { name: 'Reactivate', exact: true }).click();
    await expect(courseRow.getByText('Active', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Events', exact: true }).click();
    await page.getByPlaceholder('Event name').fill('Browser QA Event');
    await page.getByPlaceholder('City', { exact: true }).fill('Abuja');
    await page.getByPlaceholder('Venue', { exact: true }).fill('Test Venue');
    await page.locator('input[name="date"]').fill('2027-01-01');
    await page.locator('input[name="time"]').fill('10:00');
    await page.getByPlaceholder('Capacity', { exact: true }).fill('100');
    await page.getByRole('button', { name: 'Create event', exact: true }).click();
    await expect(page.locator('.manage-row').filter({ hasText: 'Browser QA Event' })).toBeVisible();
    await expect(page.getByPlaceholder('Event name')).toHaveValue('');
    const eventRow = page.locator('.manage-row').filter({ hasText: 'Browser QA Event' });
    await eventRow.getByRole('button', { name: 'Edit', exact: true }).click();
    await page.getByRole('dialog').getByRole('spinbutton', { name: 'Capacity' }).fill('150');
    await page.getByRole('dialog').getByRole('textbox', { name: 'Venue' }).fill('Updated Test Venue');
    await page.getByRole('dialog').getByRole('button', { name: 'Save changes' }).click();
    await expect(eventRow).toContainText('Capacity 150');
    await expect(eventRow).toContainText('Updated Test Venue');
    await eventRow.getByRole('button', { name: 'View inquiries' }).click();
    await expect(page.getByRole('combobox', { name: 'Event', exact: true })).not.toHaveValue('');
    await expect(page.getByText('No matching inquiries.', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Clear filters' }).click();
    await page.getByRole('button', { name: 'Overview', exact: true }).click();
    await page.getByRole('textbox', { name: 'Search inquiries' }).fill('browser-student');
    await page.getByRole('combobox', { name: 'Inquiry status', exact: true }).selectOption('Closed');
    await expect(page.locator('.admin-stats article').first().locator('strong')).toHaveText('0');
    await page.getByRole('button', { name: 'Clear filters' }).click();
    await page.getByRole('textbox', { name: 'Search inquiries' }).fill('browser-student');
    await expect(page.locator('.admin-stats article').first().locator('strong')).toHaveText('1');
    await expect(page.locator('.revenue-table tbody tr').first()).toContainText('₦');
    await page.getByRole('button', { name: /Student portal/ }).click();
    await page.getByRole('textbox', { name: /Full name/ }).fill('Signed In Student');
    await page.getByRole('textbox', { name: /Email address/ }).fill('signed-in@example.com');
    await page.getByRole('textbox', { name: /Phone number/ }).fill('+234 801 234 5678');
    await page.getByRole('textbox', { name: /Your location/ }).fill('Abuja, Nigeria');
    await page.getByRole('textbox', { name: 'Search courses' }).fill('Browser QA Course');
    await page.locator('.course-result').filter({ hasText: 'Browser QA Course' }).click();
    await page.getByRole('combobox', { name: /Preferred intake/ }).selectOption({ label: 'January 2027' });
    await page.getByRole('combobox', { name: /Preferred study destination/ }).selectOption('United Kingdom');
    await page.locator('select[name="event_id"]').selectOption({ label: 'Browser QA Event · Abuja · 1 Jan 2027' });
    await page.getByRole('button', { name: 'Send my interest' }).click();
    await expect(page.locator('.success')).toContainText('Reference: TGM-');
    await expect(page.getByRole('alert')).toHaveCount(0);
    await page.getByRole('button', { name: 'Admin', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Overview', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Sign out' }).click();
    await expect(page.getByRole('heading', { name: 'Admin sign in' })).toBeVisible();
    expect(errors).toEqual([]);
  });

  test('mobile renders without horizontal overflow and admin deep links load', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto('/');
    await expect(page.getByRole('textbox', { name: /Full name/ })).toBeVisible();
    await page.getByRole('textbox', { name: 'Search courses' }).fill('Science');
    await expect(page.locator('.course-result').first()).toBeVisible();
    const fits = await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth);
    expect(fits).toBe(true);
    await page.screenshot({ path: 'test-results/student-mobile.png', fullPage: true });
    await page.goto('/admin/');
    await expect(page.getByRole('heading', { name: 'Admin sign in' })).toBeVisible();
  });

  test('browsable API loads styled forms, supports browser login, and protects staff data', async ({ page }) => {
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('/api/');
    await expect(page.getByRole('heading', { name: 'Api Root', exact: true })).toBeVisible();
    const stylesheet = await page.request.get('/static/rest_framework/css/bootstrap.min.css');
    expect(stylesheet.status()).toBe(200);
    await page.goto('/api/admin/courses/');
    await expect(page.locator('.response-info')).toContainText('403');
    await page.getByRole('link', { name: 'Log in', exact: true }).click();
    await page.getByLabel('Username').fill('e2e-admin');
    await page.getByLabel('Password').fill('E2eOnly934!');
    await page.getByRole('button', { name: 'Log in', exact: true }).click();
    await expect(page).toHaveURL(/\/api\/admin\/courses\/$/);
    await expect(page.locator('.response-info')).toContainText('200');
    await expect(page.locator('input[name="name"]').first()).toBeVisible();
    await page.goto('/api/inquiries/');
    await expect(page.locator('input[name="full_name"]').first()).toBeVisible();
    await expect(page.locator('textarea[name="message"]').first()).toBeVisible();
    await page.goto('/admin/');
    await expect(page.getByRole('heading', { name: 'Overview', exact: true })).toBeVisible();
    await page.screenshot({ path: 'test-results/admin-overview.png', fullPage: true });
    await page.setViewportSize({ width: 375, height: 812 });
    await page.getByRole('button', { name: 'Courses', exact: true }).click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: 'test-results/admin-mobile.png', fullPage: true });
    expect(errors).toEqual([]);
  });

  test('invalid phone is rejected before posting and course search uses the API', async ({ page }) => {
    let submissions = 0;
    page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/api/inquiries/')) submissions++; });
    await page.goto('/');
    await page.getByRole('textbox', { name: /Full name/ }).fill('Validation Student');
    await page.getByRole('textbox', { name: /Email address/ }).fill('validation@example.com');
    await page.getByRole('textbox', { name: /Phone number/ }).fill('-------');
    await page.getByRole('textbox', { name: /Your location/ }).fill('Lagos, Nigeria');
    const searchResponse = page.waitForResponse(response => response.url().includes('/api/courses/?q=Computer') && response.status() === 200);
    await page.getByRole('textbox', { name: 'Search courses' }).fill('Computer');
    await searchResponse;
    await page.locator('.course-result').filter({ hasText: 'Computer Science' }).click();
    await page.getByRole('combobox', { name: /Preferred intake/ }).selectOption({ label: 'January 2027' });
    await page.getByRole('combobox', { name: /Preferred study destination/ }).selectOption('United Kingdom');
    await page.locator('select[name="event_id"]').selectOption({ index: 1 });
    await page.getByRole('button', { name: 'Send my interest' }).click();
    await expect(page.getByRole('alert')).toContainText('7 to 15 digits');
    expect(submissions).toBe(0);
  });

  test('seeded analytics, table pagination, sorting and CSV export work together', async ({ page }) => {
    await page.goto('/admin/');
    await page.getByRole('textbox', { name: 'Username' }).fill('e2e-admin');
    await page.getByLabel('Password', { exact: true }).fill('E2eOnly934!');
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(page.locator('.admin-stats article').first().locator('strong')).toHaveText('242');
    await expect(page.getByRole('img', { name: 'Daily inquiry count over time' })).toBeVisible();
    await expect(page.locator('.revenue-table tbody tr')).toHaveCount(21);
    await page.getByRole('button', { name: 'Inquiries', exact: true }).click();
    await expect(page.locator('tbody tr')).toHaveCount(20);
    await expect(page.getByText('Page 1 of 13', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Next page' }).click();
    await expect(page.getByText('Page 2 of 13', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Sort by student', exact: true }).click();
    await expect(page.getByText('Page 1 of 13', { exact: true })).toBeVisible();
    await expect(page.getByRole('combobox', { name: 'Inquiry order' })).toHaveValue('full_name');
    await page.getByRole('textbox', { name: 'Search inquiries' }).fill('student0001@example.com');
    await expect(page.locator('tbody tr')).toHaveCount(1);
    await expect(page.locator('tbody tr')).toContainText('DEMO-000001');
    const response = await page.request.get(await page.getByRole('link', { name: 'Export CSV' }).getAttribute('href'));
    expect(response.status()).toBe(200);
    const csv = await response.text();
    expect(csv).toContain('student0001@example.com');
    expect(csv).not.toContain('student0002@example.com');
  });
  test('report pie and bar charts drill down, clear filters, and fit mobile/print layouts', async ({ page }) => {
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('/admin/');
    await page.getByRole('textbox', { name: 'Username' }).fill('e2e-admin');
    await page.getByLabel('Password', { exact: true }).fill('E2eOnly934!');
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Overview', exact: true })).toBeVisible();
    const expected = await (await page.request.get('/api/admin/dashboard/')).json();
    await page.getByRole('button', { name: 'Reports', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Reports', exact: true })).toBeVisible();
    await expect(page.getByRole('img', { name: 'Inquiry status pie chart' })).toBeVisible();
    await expect(page.getByRole('img', { name: 'Study destinations pie chart' })).toBeVisible();
    await expect(page.getByRole('group', { name: 'Course demand bar chart' })).toBeVisible();
    await expect(page.getByRole('group', { name: 'Potential revenue bar chart' })).toContainText('₦');
    await page.getByRole('button', { name: 'Filter inquiry status by Converted', exact: true }).click();
    await expect(page.getByRole('combobox', { name: 'Inquiry status', exact: true })).toHaveValue('Converted');
    await expect(page.locator('.admin-stats article').first().locator('strong')).toHaveText(String(expected.status.find(row => row.status === 'Converted').total));
    await page.getByRole('button', { name: 'Clear filters' }).click();
    await expect(page.locator('.admin-stats article').first().locator('strong')).toHaveText(String(expected.total));
    await page.getByRole('group', { name: 'Course demand bar chart' }).getByRole('button', { name: /^Filter by Computer Science,/ }).click();
    await expect(page.getByRole('combobox', { name: 'Course', exact: true })).not.toHaveValue('');
    await expect(page.locator('.admin-stats article').first().locator('strong')).toHaveText(String(expected.courses.find(row => row.course__name === 'Computer Science').total));
    await page.getByRole('button', { name: 'Clear filters' }).click();
    await expect(page.locator('.admin-stats article').first().locator('strong')).toHaveText(String(expected.total));
    await page.screenshot({ path: 'test-results/admin-reports-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 375, height: 812 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await expect(page.getByRole('img', { name: 'Inquiry status pie chart' })).toBeVisible();
    await page.screenshot({ path: 'test-results/admin-reports-mobile.png', fullPage: true });
    await page.emulateMedia({ media: 'print' });
    await expect(page.locator('.admin-side')).not.toBeVisible();
    await expect(page.locator('.admin-filters')).not.toBeVisible();
    await expect(page.getByRole('img', { name: 'Inquiry status pie chart' })).toBeVisible();
    expect(errors).toEqual([]);
  });
});
